server:
  port: 8082
spring:
  application:
    name: movies-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mariadb:3306/db_movies
    username: test
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movies Microservice
